name: Build Debian Packages

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install makedeb
      run: |
        export TERM=xterm
        export MAKEDEB_RELEASE='makedeb'
        bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"
    - name: Build package
      run: |
        while read repo; do
          git clone $repo
          repo_name="$(basename $repo .git)"
          cd $repo_name
          makedeb -s
          cd ..
        done < repositories.txt
        mkdir -p incoming
        find . -name '*.deb' -exec mv {} incoming/ \;
    - name: Configure Git
      run: |
        git config --global user.email "40393784+SoftwareRat@users.noreply.github.com"
        git config --global user.name "SoftwareRat"
    - name: Commit and Push
      run: |
        git add incoming/
        git commit -m "Build new Debian packages"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: incoming
