name: Build Debian Packages

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      with:
        token: ${{ secrets.my_secret_github_access }}
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        export TERM=xterm
        export MAKEDEB_RELEASE='makedeb'
        bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"
        sleep 2
        sudo apt-get install -y reprepro
    
    - name: Build and prepare packages
      run: |
        while read repo; do
          git clone $repo
          repo_name="$(basename $repo .git)"
          cd $repo_name
          makedeb -s
          cd ..
        done < repositories.txt
        
        mkdir -p repo
        mv *.deb repo/
        reprepro -b repo includedeb stretch repo/*.deb
        
    - name: Configure Git
      run: |
        git config --global user.email "40393784+SoftwareRat@users.noreply.github.com"
        git config --global user.name "SoftwareRat"
    - name: Commit and Push
      # Only run on main branch push (e.g. pull request merge).
      if: github.event_name == 'push' && github.event.head_commit.message != 'Build new Debian packages'
      run: |
        git add repo/
        git commit -m "Build new Debian packages"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.my_secret_github_access }}
