name: Build Debian Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install makedeb
      run: |
        export MAKEDEB_RELEASE='makedeb'
        bash -c "$(wget -qO - 'https://shlink.makedeb.org/install')"

    - name: Build package
      run: |
        while read repo; do
          git clone $repo
          cd $(basename $repo)
          makedeb -s
          cd ..
        done < repositories.txt
        mkdir -p incoming
        find . -name '*.deb' -exec mv {} incoming/ \;

    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: incoming
